// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {mcp} from '../models';
import {importer} from '../models';

export function AddServer(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<db.MCPServer>;

export function CallTool(arg1:number,arg2:string,arg3:string):Promise<mcp.ToolCallResult>;

export function ConnectServer(arg1:number):Promise<void>;

export function DeleteServer(arg1:number):Promise<void>;

export function DisconnectServer(arg1:number):Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetClaudeDesktopConfigPath():Promise<string>;

export function GetCursorConfigPath():Promise<string>;

export function GetEvents(arg1:number):Promise<Array<db.MCPEvent>>;

export function GetLocalClaudeConfigPath():Promise<string>;

export function GetServers():Promise<Array<db.MCPServer>>;

export function GetTools(arg1:number):Promise<Array<mcp.Tool>>;

export function GetWindsurfConfigPath():Promise<string>;

export function ImportClaudeDesktopConfig(arg1:string):Promise<importer.ImportResult>;

export function OpenFilePicker():Promise<string>;

export function UpdateServer(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<db.MCPServer>;
