// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServer(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddServer'](arg1, arg2, arg3, arg4, arg5);
}

export function CallTool(arg1, arg2, arg3) {
  return window['go']['main']['App']['CallTool'](arg1, arg2, arg3);
}

export function ConnectServer(arg1) {
  return window['go']['main']['App']['ConnectServer'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function DisconnectServer(arg1) {
  return window['go']['main']['App']['DisconnectServer'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetClaudeDesktopConfigPath() {
  return window['go']['main']['App']['GetClaudeDesktopConfigPath']();
}

export function GetCursorConfigPath() {
  return window['go']['main']['App']['GetCursorConfigPath']();
}

export function GetEvents(arg1) {
  return window['go']['main']['App']['GetEvents'](arg1);
}

export function GetLocalClaudeConfigPath() {
  return window['go']['main']['App']['GetLocalClaudeConfigPath']();
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function GetTools(arg1) {
  return window['go']['main']['App']['GetTools'](arg1);
}

export function GetWindsurfConfigPath() {
  return window['go']['main']['App']['GetWindsurfConfigPath']();
}

export function ImportClaudeDesktopConfig(arg1) {
  return window['go']['main']['App']['ImportClaudeDesktopConfig'](arg1);
}

export function OpenFilePicker() {
  return window['go']['main']['App']['OpenFilePicker']();
}

export function UpdateServer(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateServer'](arg1, arg2, arg3, arg4, arg5);
}
